---
- name: Install Jenkins on EC2
  hosts: web
  become: yes

  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started
